// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reco_service.proto

package com.plato.recoserver.grpc.service;

public final class RecoServer {
  private RecoServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_recoserver_grpc_service_RecoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_recoserver_grpc_service_RecoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_recoserver_grpc_service_RecoItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_recoserver_grpc_service_RecoItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_recoserver_grpc_service_RecoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_recoserver_grpc_service_RecoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_recoserver_grpc_service_RecData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_recoserver_grpc_service_RecData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022reco_service.proto\022!com.plato.recoserv" +
      "er.grpc.service\"\343\002\n\013RecoRequest\022\022\n\nreque" +
      "st_id\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\017\n\007user_i" +
      "d\030\003 \001(\003\022\022\n\nvip_status\030\004 \001(\t\022\021\n\trec_scene" +
      "\030\005 \001(\t\022\022\n\nsession_id\030\006 \001(\t\022\013\n\003num\030\007 \001(\005\022" +
      "\017\n\007page_id\030\010 \001(\t\022\020\n\010page_num\030\t \001(\005\022=\n\010pl" +
      "atform\030\n \001(\0162+.com.plato.recoserver.grpc" +
      ".service.Platform\022\n\n\002os\030\013 \001(\t\022\017\n\007network" +
      "\030\014 \001(\t\022\013\n\003gps\030\r \001(\t\022\n\n\002ip\030\016 \001(\t\022<\n\007filte" +
      "rs\030\017 \003(\0132+.com.plato.recoserver.grpc.ser" +
      "vice.RecoItem\"\242\003\n\010RecoItem\022\017\n\007item_id\030\001 " +
      "\001(\003\022B\n\004type\030\002 \001(\01624.com.plato.recoserver" +
      ".grpc.service.RecoItem.ItemType\022\025\n\ritem_" +
      "tracking\030\003 \001(\t\022\020\n\010item_id2\030\004 \001(\t\"\227\002\n\010Ite" +
      "mType\022\013\n\007UNKNOWN\020\000\022\013\n\007PRODUCT\020\001\022\013\n\007ARTIC" +
      "LE\020\002\022\016\n\nCOLLECTION\020\003\022\014\n\010FAVORITE\020\004\022\020\n\014HE" +
      "LLORFIMAGE\020\005\022\025\n\021HELLORfLOCAlIMAGE\020\006\022\020\n\014H" +
      "ELLORFVIDEO\020\007\022\026\n\022HELLORFIMAGESHUTER\020\010\022\026\n" +
      "\022HELLORFALBUMSHUTER\020\t\022\026\n\022HELLORFVIDEOSHU" +
      "TER\020\n\022\021\n\rHELLORFALBUMS\020\021\022\016\n\nLIVECOURSE\020\024" +
      "\022\017\n\013VIDEOCOURSE\020\025\022\017\n\013MEMBERVIDEO\020\026\"k\n\014Re" +
      "coResponse\022\014\n\004code\030\001 \001(\t\022\017\n\007message\030\002 \001(" +
      "\t\022<\n\010rec_data\030\003 \003(\0132*.com.plato.recoserv" +
      "er.grpc.service.RecData\"H\n\007RecData\022=\n\010re" +
      "c_item\030\001 \003(\0132+.com.plato.recoserver.grpc" +
      ".service.RecoItem*Z\n\010Platform\022\024\n\020PLATFOR" +
      "M_UNKNOWN\020\000\022\020\n\014PLATFORM_IOS\020\001\022\024\n\020PLATFOR" +
      "M_ANDROID\020\002\022\020\n\014PLATFORM_PCW\020\0032\205\001\n\021RecoSe" +
      "rverService\022p\n\rgetRecoResult\022..com.plato" +
      ".recoserver.grpc.service.RecoRequest\032/.c" +
      "om.plato.recoserver.grpc.service.RecoRes" +
      "ponseB1\n!com.plato.recoserver.grpc.servi" +
      "ceB\nRecoServerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_plato_recoserver_grpc_service_RecoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_plato_recoserver_grpc_service_RecoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_recoserver_grpc_service_RecoRequest_descriptor,
        new java.lang.String[] { "RequestId", "DeviceId", "UserId", "VipStatus", "RecScene", "SessionId", "Num", "PageId", "PageNum", "Platform", "Os", "Network", "Gps", "Ip", "Filters", });
    internal_static_com_plato_recoserver_grpc_service_RecoItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_plato_recoserver_grpc_service_RecoItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_recoserver_grpc_service_RecoItem_descriptor,
        new java.lang.String[] { "ItemId", "Type", "ItemTracking", "ItemId2", });
    internal_static_com_plato_recoserver_grpc_service_RecoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_plato_recoserver_grpc_service_RecoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_recoserver_grpc_service_RecoResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "RecData", });
    internal_static_com_plato_recoserver_grpc_service_RecData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_plato_recoserver_grpc_service_RecData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_recoserver_grpc_service_RecData_descriptor,
        new java.lang.String[] { "RecItem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
