// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reco_service.proto

package com.plato.recoserver.grpc.service;

/**
 * Protobuf type {@code com.plato.recoserver.grpc.service.RecoRequest}
 */
public final class RecoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.recoserver.grpc.service.RecoRequest)
    RecoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecoRequest.newBuilder() to construct.
  private RecoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecoRequest() {
    requestId_ = "";
    deviceId_ = "";
    vipStatus_ = "";
    recScene_ = "";
    sessionId_ = "";
    pageId_ = "";
    platform_ = 0;
    os_ = "";
    network_ = "";
    gps_ = "";
    ip_ = "";
    filters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecoRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 24: {

            userId_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            vipStatus_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            recScene_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            sessionId_ = s;
            break;
          }
          case 56: {

            num_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            pageId_ = s;
            break;
          }
          case 72: {

            pageNum_ = input.readInt32();
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            platform_ = rawValue;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            os_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            network_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            gps_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              filters_ = new java.util.ArrayList<com.plato.recoserver.grpc.service.RecoItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            filters_.add(
                input.readMessage(com.plato.recoserver.grpc.service.RecoItem.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        filters_ = java.util.Collections.unmodifiableList(filters_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.recoserver.grpc.service.RecoServer.internal_static_com_plato_recoserver_grpc_service_RecoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.recoserver.grpc.service.RecoServer.internal_static_com_plato_recoserver_grpc_service_RecoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.recoserver.grpc.service.RecoRequest.class, com.plato.recoserver.grpc.service.RecoRequest.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <pre>
   *本次请求的唯一标识，保证每次请求唯一
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *本次请求的唯一标识，保证每次请求唯一
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object deviceId_;
  /**
   * <pre>
   *请求用户的设备id
   * </pre>
   *
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *请求用户的设备id
   * </pre>
   *
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 3;
  private long userId_;
  /**
   * <pre>
   *登陆用户的user_id
   * </pre>
   *
   * <code>int64 user_id = 3;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int VIP_STATUS_FIELD_NUMBER = 4;
  private volatile java.lang.Object vipStatus_;
  /**
   * <pre>
   *用户的会员状态
   * </pre>
   *
   * <code>string vip_status = 4;</code>
   * @return The vipStatus.
   */
  @java.lang.Override
  public java.lang.String getVipStatus() {
    java.lang.Object ref = vipStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vipStatus_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户的会员状态
   * </pre>
   *
   * <code>string vip_status = 4;</code>
   * @return The bytes for vipStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVipStatusBytes() {
    java.lang.Object ref = vipStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vipStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REC_SCENE_FIELD_NUMBER = 5;
  private volatile java.lang.Object recScene_;
  /**
   * <pre>
   *推荐场景
   * </pre>
   *
   * <code>string rec_scene = 5;</code>
   * @return The recScene.
   */
  @java.lang.Override
  public java.lang.String getRecScene() {
    java.lang.Object ref = recScene_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recScene_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *推荐场景
   * </pre>
   *
   * <code>string rec_scene = 5;</code>
   * @return The bytes for recScene.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecSceneBytes() {
    java.lang.Object ref = recScene_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recScene_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object sessionId_;
  /**
   * <pre>
   *用户连续请求的唯一标识
   * </pre>
   *
   * <code>string session_id = 6;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户连续请求的唯一标识
   * </pre>
   *
   * <code>string session_id = 6;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_FIELD_NUMBER = 7;
  private int num_;
  /**
   * <pre>
   *本次请求需要返回的数量
   * </pre>
   *
   * <code>int32 num = 7;</code>
   * @return The num.
   */
  @java.lang.Override
  public int getNum() {
    return num_;
  }

  public static final int PAGE_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object pageId_;
  /**
   * <pre>
   *用户请求的页面标识
   * </pre>
   *
   * <code>string page_id = 8;</code>
   * @return The pageId.
   */
  @java.lang.Override
  public java.lang.String getPageId() {
    java.lang.Object ref = pageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户请求的页面标识
   * </pre>
   *
   * <code>string page_id = 8;</code>
   * @return The bytes for pageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPageIdBytes() {
    java.lang.Object ref = pageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_NUM_FIELD_NUMBER = 9;
  private int pageNum_;
  /**
   * <pre>
   *用户当前请求所在页的页码
   * </pre>
   *
   * <code>int32 page_num = 9;</code>
   * @return The pageNum.
   */
  @java.lang.Override
  public int getPageNum() {
    return pageNum_;
  }

  public static final int PLATFORM_FIELD_NUMBER = 10;
  private int platform_;
  /**
   * <pre>
   *请求用户的平台类型
   * </pre>
   *
   * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
   * @return The enum numeric value on the wire for platform.
   */
  @java.lang.Override public int getPlatformValue() {
    return platform_;
  }
  /**
   * <pre>
   *请求用户的平台类型
   * </pre>
   *
   * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
   * @return The platform.
   */
  @java.lang.Override public com.plato.recoserver.grpc.service.Platform getPlatform() {
    @SuppressWarnings("deprecation")
    com.plato.recoserver.grpc.service.Platform result = com.plato.recoserver.grpc.service.Platform.valueOf(platform_);
    return result == null ? com.plato.recoserver.grpc.service.Platform.UNRECOGNIZED : result;
  }

  public static final int OS_FIELD_NUMBER = 11;
  private volatile java.lang.Object os_;
  /**
   * <pre>
   *请求用户的设备操作系统
   * </pre>
   *
   * <code>string os = 11;</code>
   * @return The os.
   */
  @java.lang.Override
  public java.lang.String getOs() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      os_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *请求用户的设备操作系统
   * </pre>
   *
   * <code>string os = 11;</code>
   * @return The bytes for os.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsBytes() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      os_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_FIELD_NUMBER = 12;
  private volatile java.lang.Object network_;
  /**
   * <pre>
   *用户的网络状态
   * </pre>
   *
   * <code>string network = 12;</code>
   * @return The network.
   */
  @java.lang.Override
  public java.lang.String getNetwork() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      network_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户的网络状态
   * </pre>
   *
   * <code>string network = 12;</code>
   * @return The bytes for network.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkBytes() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      network_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GPS_FIELD_NUMBER = 13;
  private volatile java.lang.Object gps_;
  /**
   * <pre>
   *用户地理位置，经纬度表示用英文逗号分隔
   * </pre>
   *
   * <code>string gps = 13;</code>
   * @return The gps.
   */
  @java.lang.Override
  public java.lang.String getGps() {
    java.lang.Object ref = gps_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gps_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户地理位置，经纬度表示用英文逗号分隔
   * </pre>
   *
   * <code>string gps = 13;</code>
   * @return The bytes for gps.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGpsBytes() {
    java.lang.Object ref = gps_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gps_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 14;
  private volatile java.lang.Object ip_;
  /**
   * <pre>
   *请求用户的ip地址
   * </pre>
   *
   * <code>string ip = 14;</code>
   * @return The ip.
   */
  @java.lang.Override
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *请求用户的ip地址
   * </pre>
   *
   * <code>string ip = 14;</code>
   * @return The bytes for ip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTERS_FIELD_NUMBER = 15;
  private java.util.List<com.plato.recoserver.grpc.service.RecoItem> filters_;
  /**
   * <pre>
   *本次请求需要过滤的内容
   * </pre>
   *
   * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
   */
  @java.lang.Override
  public java.util.List<com.plato.recoserver.grpc.service.RecoItem> getFiltersList() {
    return filters_;
  }
  /**
   * <pre>
   *本次请求需要过滤的内容
   * </pre>
   *
   * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.plato.recoserver.grpc.service.RecoItemOrBuilder> 
      getFiltersOrBuilderList() {
    return filters_;
  }
  /**
   * <pre>
   *本次请求需要过滤的内容
   * </pre>
   *
   * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
   */
  @java.lang.Override
  public int getFiltersCount() {
    return filters_.size();
  }
  /**
   * <pre>
   *本次请求需要过滤的内容
   * </pre>
   *
   * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
   */
  @java.lang.Override
  public com.plato.recoserver.grpc.service.RecoItem getFilters(int index) {
    return filters_.get(index);
  }
  /**
   * <pre>
   *本次请求需要过滤的内容
   * </pre>
   *
   * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
   */
  @java.lang.Override
  public com.plato.recoserver.grpc.service.RecoItemOrBuilder getFiltersOrBuilder(
      int index) {
    return filters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
    }
    if (userId_ != 0L) {
      output.writeInt64(3, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vipStatus_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, vipStatus_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recScene_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, recScene_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sessionId_);
    }
    if (num_ != 0) {
      output.writeInt32(7, num_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pageId_);
    }
    if (pageNum_ != 0) {
      output.writeInt32(9, pageNum_);
    }
    if (platform_ != com.plato.recoserver.grpc.service.Platform.PLATFORM_UNKNOWN.getNumber()) {
      output.writeEnum(10, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, os_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, network_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gps_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, gps_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, ip_);
    }
    for (int i = 0; i < filters_.size(); i++) {
      output.writeMessage(15, filters_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vipStatus_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, vipStatus_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recScene_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, recScene_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sessionId_);
    }
    if (num_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, num_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pageId_);
    }
    if (pageNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, pageNum_);
    }
    if (platform_ != com.plato.recoserver.grpc.service.Platform.PLATFORM_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, os_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, network_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gps_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, gps_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, ip_);
    }
    for (int i = 0; i < filters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, filters_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.recoserver.grpc.service.RecoRequest)) {
      return super.equals(obj);
    }
    com.plato.recoserver.grpc.service.RecoRequest other = (com.plato.recoserver.grpc.service.RecoRequest) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getVipStatus()
        .equals(other.getVipStatus())) return false;
    if (!getRecScene()
        .equals(other.getRecScene())) return false;
    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (getNum()
        != other.getNum()) return false;
    if (!getPageId()
        .equals(other.getPageId())) return false;
    if (getPageNum()
        != other.getPageNum()) return false;
    if (platform_ != other.platform_) return false;
    if (!getOs()
        .equals(other.getOs())) return false;
    if (!getNetwork()
        .equals(other.getNetwork())) return false;
    if (!getGps()
        .equals(other.getGps())) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (!getFiltersList()
        .equals(other.getFiltersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + VIP_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getVipStatus().hashCode();
    hash = (37 * hash) + REC_SCENE_FIELD_NUMBER;
    hash = (53 * hash) + getRecScene().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + NUM_FIELD_NUMBER;
    hash = (53 * hash) + getNum();
    hash = (37 * hash) + PAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPageId().hashCode();
    hash = (37 * hash) + PAGE_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getPageNum();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    hash = (37 * hash) + OS_FIELD_NUMBER;
    hash = (53 * hash) + getOs().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + getNetwork().hashCode();
    hash = (37 * hash) + GPS_FIELD_NUMBER;
    hash = (53 * hash) + getGps().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    if (getFiltersCount() > 0) {
      hash = (37 * hash) + FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + getFiltersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.recoserver.grpc.service.RecoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.recoserver.grpc.service.RecoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.recoserver.grpc.service.RecoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.recoserver.grpc.service.RecoRequest)
      com.plato.recoserver.grpc.service.RecoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.recoserver.grpc.service.RecoServer.internal_static_com_plato_recoserver_grpc_service_RecoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.recoserver.grpc.service.RecoServer.internal_static_com_plato_recoserver_grpc_service_RecoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.recoserver.grpc.service.RecoRequest.class, com.plato.recoserver.grpc.service.RecoRequest.Builder.class);
    }

    // Construct using com.plato.recoserver.grpc.service.RecoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFiltersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      deviceId_ = "";

      userId_ = 0L;

      vipStatus_ = "";

      recScene_ = "";

      sessionId_ = "";

      num_ = 0;

      pageId_ = "";

      pageNum_ = 0;

      platform_ = 0;

      os_ = "";

      network_ = "";

      gps_ = "";

      ip_ = "";

      if (filtersBuilder_ == null) {
        filters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        filtersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.recoserver.grpc.service.RecoServer.internal_static_com_plato_recoserver_grpc_service_RecoRequest_descriptor;
    }

    @java.lang.Override
    public com.plato.recoserver.grpc.service.RecoRequest getDefaultInstanceForType() {
      return com.plato.recoserver.grpc.service.RecoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.recoserver.grpc.service.RecoRequest build() {
      com.plato.recoserver.grpc.service.RecoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.recoserver.grpc.service.RecoRequest buildPartial() {
      com.plato.recoserver.grpc.service.RecoRequest result = new com.plato.recoserver.grpc.service.RecoRequest(this);
      int from_bitField0_ = bitField0_;
      result.requestId_ = requestId_;
      result.deviceId_ = deviceId_;
      result.userId_ = userId_;
      result.vipStatus_ = vipStatus_;
      result.recScene_ = recScene_;
      result.sessionId_ = sessionId_;
      result.num_ = num_;
      result.pageId_ = pageId_;
      result.pageNum_ = pageNum_;
      result.platform_ = platform_;
      result.os_ = os_;
      result.network_ = network_;
      result.gps_ = gps_;
      result.ip_ = ip_;
      if (filtersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          filters_ = java.util.Collections.unmodifiableList(filters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.filters_ = filters_;
      } else {
        result.filters_ = filtersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.recoserver.grpc.service.RecoRequest) {
        return mergeFrom((com.plato.recoserver.grpc.service.RecoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.recoserver.grpc.service.RecoRequest other) {
      if (other == com.plato.recoserver.grpc.service.RecoRequest.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getVipStatus().isEmpty()) {
        vipStatus_ = other.vipStatus_;
        onChanged();
      }
      if (!other.getRecScene().isEmpty()) {
        recScene_ = other.recScene_;
        onChanged();
      }
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.getNum() != 0) {
        setNum(other.getNum());
      }
      if (!other.getPageId().isEmpty()) {
        pageId_ = other.pageId_;
        onChanged();
      }
      if (other.getPageNum() != 0) {
        setPageNum(other.getPageNum());
      }
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (!other.getOs().isEmpty()) {
        os_ = other.os_;
        onChanged();
      }
      if (!other.getNetwork().isEmpty()) {
        network_ = other.network_;
        onChanged();
      }
      if (!other.getGps().isEmpty()) {
        gps_ = other.gps_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (filtersBuilder_ == null) {
        if (!other.filters_.isEmpty()) {
          if (filters_.isEmpty()) {
            filters_ = other.filters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFiltersIsMutable();
            filters_.addAll(other.filters_);
          }
          onChanged();
        }
      } else {
        if (!other.filters_.isEmpty()) {
          if (filtersBuilder_.isEmpty()) {
            filtersBuilder_.dispose();
            filtersBuilder_ = null;
            filters_ = other.filters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            filtersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFiltersFieldBuilder() : null;
          } else {
            filtersBuilder_.addAllMessages(other.filters_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.plato.recoserver.grpc.service.RecoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.plato.recoserver.grpc.service.RecoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     *本次请求的唯一标识，保证每次请求唯一
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *本次请求的唯一标识，保证每次请求唯一
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *本次请求的唯一标识，保证每次请求唯一
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *本次请求的唯一标识，保证每次请求唯一
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *本次请求的唯一标识，保证每次请求唯一
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     *请求用户的设备id
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *请求用户的设备id
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *请求用户的设备id
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的设备id
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的设备id
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     *登陆用户的user_id
     * </pre>
     *
     * <code>int64 user_id = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     *登陆用户的user_id
     * </pre>
     *
     * <code>int64 user_id = 3;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *登陆用户的user_id
     * </pre>
     *
     * <code>int64 user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object vipStatus_ = "";
    /**
     * <pre>
     *用户的会员状态
     * </pre>
     *
     * <code>string vip_status = 4;</code>
     * @return The vipStatus.
     */
    public java.lang.String getVipStatus() {
      java.lang.Object ref = vipStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vipStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户的会员状态
     * </pre>
     *
     * <code>string vip_status = 4;</code>
     * @return The bytes for vipStatus.
     */
    public com.google.protobuf.ByteString
        getVipStatusBytes() {
      java.lang.Object ref = vipStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vipStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户的会员状态
     * </pre>
     *
     * <code>string vip_status = 4;</code>
     * @param value The vipStatus to set.
     * @return This builder for chaining.
     */
    public Builder setVipStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vipStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户的会员状态
     * </pre>
     *
     * <code>string vip_status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVipStatus() {
      
      vipStatus_ = getDefaultInstance().getVipStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户的会员状态
     * </pre>
     *
     * <code>string vip_status = 4;</code>
     * @param value The bytes for vipStatus to set.
     * @return This builder for chaining.
     */
    public Builder setVipStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vipStatus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recScene_ = "";
    /**
     * <pre>
     *推荐场景
     * </pre>
     *
     * <code>string rec_scene = 5;</code>
     * @return The recScene.
     */
    public java.lang.String getRecScene() {
      java.lang.Object ref = recScene_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recScene_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *推荐场景
     * </pre>
     *
     * <code>string rec_scene = 5;</code>
     * @return The bytes for recScene.
     */
    public com.google.protobuf.ByteString
        getRecSceneBytes() {
      java.lang.Object ref = recScene_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recScene_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *推荐场景
     * </pre>
     *
     * <code>string rec_scene = 5;</code>
     * @param value The recScene to set.
     * @return This builder for chaining.
     */
    public Builder setRecScene(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recScene_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *推荐场景
     * </pre>
     *
     * <code>string rec_scene = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecScene() {
      
      recScene_ = getDefaultInstance().getRecScene();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *推荐场景
     * </pre>
     *
     * <code>string rec_scene = 5;</code>
     * @param value The bytes for recScene to set.
     * @return This builder for chaining.
     */
    public Builder setRecSceneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recScene_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <pre>
     *用户连续请求的唯一标识
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户连续请求的唯一标识
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户连续请求的唯一标识
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户连续请求的唯一标识
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户连续请求的唯一标识
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionId_ = value;
      onChanged();
      return this;
    }

    private int num_ ;
    /**
     * <pre>
     *本次请求需要返回的数量
     * </pre>
     *
     * <code>int32 num = 7;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }
    /**
     * <pre>
     *本次请求需要返回的数量
     * </pre>
     *
     * <code>int32 num = 7;</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(int value) {
      
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *本次请求需要返回的数量
     * </pre>
     *
     * <code>int32 num = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {
      
      num_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pageId_ = "";
    /**
     * <pre>
     *用户请求的页面标识
     * </pre>
     *
     * <code>string page_id = 8;</code>
     * @return The pageId.
     */
    public java.lang.String getPageId() {
      java.lang.Object ref = pageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户请求的页面标识
     * </pre>
     *
     * <code>string page_id = 8;</code>
     * @return The bytes for pageId.
     */
    public com.google.protobuf.ByteString
        getPageIdBytes() {
      java.lang.Object ref = pageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户请求的页面标识
     * </pre>
     *
     * <code>string page_id = 8;</code>
     * @param value The pageId to set.
     * @return This builder for chaining.
     */
    public Builder setPageId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户请求的页面标识
     * </pre>
     *
     * <code>string page_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageId() {
      
      pageId_ = getDefaultInstance().getPageId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户请求的页面标识
     * </pre>
     *
     * <code>string page_id = 8;</code>
     * @param value The bytes for pageId to set.
     * @return This builder for chaining.
     */
    public Builder setPageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pageId_ = value;
      onChanged();
      return this;
    }

    private int pageNum_ ;
    /**
     * <pre>
     *用户当前请求所在页的页码
     * </pre>
     *
     * <code>int32 page_num = 9;</code>
     * @return The pageNum.
     */
    @java.lang.Override
    public int getPageNum() {
      return pageNum_;
    }
    /**
     * <pre>
     *用户当前请求所在页的页码
     * </pre>
     *
     * <code>int32 page_num = 9;</code>
     * @param value The pageNum to set.
     * @return This builder for chaining.
     */
    public Builder setPageNum(int value) {
      
      pageNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户当前请求所在页的页码
     * </pre>
     *
     * <code>int32 page_num = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNum() {
      
      pageNum_ = 0;
      onChanged();
      return this;
    }

    private int platform_ = 0;
    /**
     * <pre>
     *请求用户的平台类型
     * </pre>
     *
     * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
     * @return The enum numeric value on the wire for platform.
     */
    @java.lang.Override public int getPlatformValue() {
      return platform_;
    }
    /**
     * <pre>
     *请求用户的平台类型
     * </pre>
     *
     * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
     * @param value The enum numeric value on the wire for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformValue(int value) {
      
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的平台类型
     * </pre>
     *
     * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
     * @return The platform.
     */
    @java.lang.Override
    public com.plato.recoserver.grpc.service.Platform getPlatform() {
      @SuppressWarnings("deprecation")
      com.plato.recoserver.grpc.service.Platform result = com.plato.recoserver.grpc.service.Platform.valueOf(platform_);
      return result == null ? com.plato.recoserver.grpc.service.Platform.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *请求用户的平台类型
     * </pre>
     *
     * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(com.plato.recoserver.grpc.service.Platform value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的平台类型
     * </pre>
     *
     * <code>.com.plato.recoserver.grpc.service.Platform platform = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      
      platform_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object os_ = "";
    /**
     * <pre>
     *请求用户的设备操作系统
     * </pre>
     *
     * <code>string os = 11;</code>
     * @return The os.
     */
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *请求用户的设备操作系统
     * </pre>
     *
     * <code>string os = 11;</code>
     * @return The bytes for os.
     */
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *请求用户的设备操作系统
     * </pre>
     *
     * <code>string os = 11;</code>
     * @param value The os to set.
     * @return This builder for chaining.
     */
    public Builder setOs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      os_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的设备操作系统
     * </pre>
     *
     * <code>string os = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearOs() {
      
      os_ = getDefaultInstance().getOs();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的设备操作系统
     * </pre>
     *
     * <code>string os = 11;</code>
     * @param value The bytes for os to set.
     * @return This builder for chaining.
     */
    public Builder setOsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      os_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object network_ = "";
    /**
     * <pre>
     *用户的网络状态
     * </pre>
     *
     * <code>string network = 12;</code>
     * @return The network.
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        network_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户的网络状态
     * </pre>
     *
     * <code>string network = 12;</code>
     * @return The bytes for network.
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户的网络状态
     * </pre>
     *
     * <code>string network = 12;</code>
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      network_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户的网络状态
     * </pre>
     *
     * <code>string network = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      
      network_ = getDefaultInstance().getNetwork();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户的网络状态
     * </pre>
     *
     * <code>string network = 12;</code>
     * @param value The bytes for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      network_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gps_ = "";
    /**
     * <pre>
     *用户地理位置，经纬度表示用英文逗号分隔
     * </pre>
     *
     * <code>string gps = 13;</code>
     * @return The gps.
     */
    public java.lang.String getGps() {
      java.lang.Object ref = gps_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gps_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户地理位置，经纬度表示用英文逗号分隔
     * </pre>
     *
     * <code>string gps = 13;</code>
     * @return The bytes for gps.
     */
    public com.google.protobuf.ByteString
        getGpsBytes() {
      java.lang.Object ref = gps_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gps_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户地理位置，经纬度表示用英文逗号分隔
     * </pre>
     *
     * <code>string gps = 13;</code>
     * @param value The gps to set.
     * @return This builder for chaining.
     */
    public Builder setGps(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gps_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户地理位置，经纬度表示用英文逗号分隔
     * </pre>
     *
     * <code>string gps = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearGps() {
      
      gps_ = getDefaultInstance().getGps();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户地理位置，经纬度表示用英文逗号分隔
     * </pre>
     *
     * <code>string gps = 13;</code>
     * @param value The bytes for gps to set.
     * @return This builder for chaining.
     */
    public Builder setGpsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gps_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <pre>
     *请求用户的ip地址
     * </pre>
     *
     * <code>string ip = 14;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *请求用户的ip地址
     * </pre>
     *
     * <code>string ip = 14;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *请求用户的ip地址
     * </pre>
     *
     * <code>string ip = 14;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的ip地址
     * </pre>
     *
     * <code>string ip = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求用户的ip地址
     * </pre>
     *
     * <code>string ip = 14;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.plato.recoserver.grpc.service.RecoItem> filters_ =
      java.util.Collections.emptyList();
    private void ensureFiltersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        filters_ = new java.util.ArrayList<com.plato.recoserver.grpc.service.RecoItem>(filters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plato.recoserver.grpc.service.RecoItem, com.plato.recoserver.grpc.service.RecoItem.Builder, com.plato.recoserver.grpc.service.RecoItemOrBuilder> filtersBuilder_;

    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public java.util.List<com.plato.recoserver.grpc.service.RecoItem> getFiltersList() {
      if (filtersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(filters_);
      } else {
        return filtersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public int getFiltersCount() {
      if (filtersBuilder_ == null) {
        return filters_.size();
      } else {
        return filtersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public com.plato.recoserver.grpc.service.RecoItem getFilters(int index) {
      if (filtersBuilder_ == null) {
        return filters_.get(index);
      } else {
        return filtersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder setFilters(
        int index, com.plato.recoserver.grpc.service.RecoItem value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFiltersIsMutable();
        filters_.set(index, value);
        onChanged();
      } else {
        filtersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder setFilters(
        int index, com.plato.recoserver.grpc.service.RecoItem.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.set(index, builderForValue.build());
        onChanged();
      } else {
        filtersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder addFilters(com.plato.recoserver.grpc.service.RecoItem value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFiltersIsMutable();
        filters_.add(value);
        onChanged();
      } else {
        filtersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder addFilters(
        int index, com.plato.recoserver.grpc.service.RecoItem value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFiltersIsMutable();
        filters_.add(index, value);
        onChanged();
      } else {
        filtersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder addFilters(
        com.plato.recoserver.grpc.service.RecoItem.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.add(builderForValue.build());
        onChanged();
      } else {
        filtersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder addFilters(
        int index, com.plato.recoserver.grpc.service.RecoItem.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.add(index, builderForValue.build());
        onChanged();
      } else {
        filtersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder addAllFilters(
        java.lang.Iterable<? extends com.plato.recoserver.grpc.service.RecoItem> values) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, filters_);
        onChanged();
      } else {
        filtersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder clearFilters() {
      if (filtersBuilder_ == null) {
        filters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        filtersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public Builder removeFilters(int index) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.remove(index);
        onChanged();
      } else {
        filtersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public com.plato.recoserver.grpc.service.RecoItem.Builder getFiltersBuilder(
        int index) {
      return getFiltersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public com.plato.recoserver.grpc.service.RecoItemOrBuilder getFiltersOrBuilder(
        int index) {
      if (filtersBuilder_ == null) {
        return filters_.get(index);  } else {
        return filtersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public java.util.List<? extends com.plato.recoserver.grpc.service.RecoItemOrBuilder> 
         getFiltersOrBuilderList() {
      if (filtersBuilder_ != null) {
        return filtersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(filters_);
      }
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public com.plato.recoserver.grpc.service.RecoItem.Builder addFiltersBuilder() {
      return getFiltersFieldBuilder().addBuilder(
          com.plato.recoserver.grpc.service.RecoItem.getDefaultInstance());
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public com.plato.recoserver.grpc.service.RecoItem.Builder addFiltersBuilder(
        int index) {
      return getFiltersFieldBuilder().addBuilder(
          index, com.plato.recoserver.grpc.service.RecoItem.getDefaultInstance());
    }
    /**
     * <pre>
     *本次请求需要过滤的内容
     * </pre>
     *
     * <code>repeated .com.plato.recoserver.grpc.service.RecoItem filters = 15;</code>
     */
    public java.util.List<com.plato.recoserver.grpc.service.RecoItem.Builder> 
         getFiltersBuilderList() {
      return getFiltersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plato.recoserver.grpc.service.RecoItem, com.plato.recoserver.grpc.service.RecoItem.Builder, com.plato.recoserver.grpc.service.RecoItemOrBuilder> 
        getFiltersFieldBuilder() {
      if (filtersBuilder_ == null) {
        filtersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.plato.recoserver.grpc.service.RecoItem, com.plato.recoserver.grpc.service.RecoItem.Builder, com.plato.recoserver.grpc.service.RecoItemOrBuilder>(
                filters_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        filters_ = null;
      }
      return filtersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.recoserver.grpc.service.RecoRequest)
  }

  // @@protoc_insertion_point(class_scope:com.plato.recoserver.grpc.service.RecoRequest)
  private static final com.plato.recoserver.grpc.service.RecoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.recoserver.grpc.service.RecoRequest();
  }

  public static com.plato.recoserver.grpc.service.RecoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecoRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecoRequest>() {
    @java.lang.Override
    public RecoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.recoserver.grpc.service.RecoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

