// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reco_service.proto

package com.plato.recoserver.grpc.service;

public interface RecoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.recoserver.grpc.service.RecoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .com.plato.recoserver.grpc.service.RecData rec_data = 3;</code>
   */
  java.util.List<com.plato.recoserver.grpc.service.RecData> 
      getRecDataList();
  /**
   * <code>repeated .com.plato.recoserver.grpc.service.RecData rec_data = 3;</code>
   */
  com.plato.recoserver.grpc.service.RecData getRecData(int index);
  /**
   * <code>repeated .com.plato.recoserver.grpc.service.RecData rec_data = 3;</code>
   */
  int getRecDataCount();
  /**
   * <code>repeated .com.plato.recoserver.grpc.service.RecData rec_data = 3;</code>
   */
  java.util.List<? extends com.plato.recoserver.grpc.service.RecDataOrBuilder> 
      getRecDataOrBuilderList();
  /**
   * <code>repeated .com.plato.recoserver.grpc.service.RecData rec_data = 3;</code>
   */
  com.plato.recoserver.grpc.service.RecDataOrBuilder getRecDataOrBuilder(
      int index);
}
